// Proyeccion compartida de mve_transventa.
//
// Se extrajo del controller historico porque la usan el CRUD de transporte
// (crear, listar, detalle, actualizar, anular) y tambien el flujo de
// encomiendas en agencia destino. Vive en un modulo neutro para no duplicarla
// ni para que el repository dependa del controller.
//
// No modificar ni una coma: los nombres de columna son el contrato del frontend.
const columnasVentaTrans = `
  CAST(r_fecemi AS VARCHAR(50)) AS r_fecemi,
  r_cod,
  r_serie,
  r_numero,
  elemento,
  tipo_operacion,
  r_cod_ref,
  r_serie_ref,
  r_numero_ref,
  CAST(r_fecemi_ref AS VARCHAR(50)) AS r_fecemi_ref,
  cliente_id_doc AS id_documento,
  cliente_id_doc,
  cliente,
  cliente_documento_id AS cliente_documento,
  cliente_documento_id,
  cliente_telefono,
  cliente_direccion_fact,
  ref_pasajero_dni,
  ref_pasajero_nombres,
  id_punto_venta,
  cliente_zona AS remitente_zona,
  cliente_zona,
  cliente_direccion AS remitente_direccion,
  cliente_direccion,
  id_ruta,
  descripcion,
  placa,
  licencia,
  id_manifiesto,
  asiento,
  pasajero_edad,
  destinatario_id_doc,
  destinatario,
  destinatario_documento_id AS destinatario_documento,
  destinatario_documento_id,
  destinatario_telefono,
  id_punto_venta_dest,
  destinatario_zona,
  destinatario_direccion,
  CAST(entrega_fecha AS VARCHAR(50)) AS entrega_fecha,
  entrega_documento_id AS entrega_documento,
  entrega_documento_id,
  entrega_nombres,
  entrega_ctrl_us,
  1 AS cantidad,
  precio_neto AS precio_unitario,
  precio_neto,
  r_gravado,
  r_exonerado,
  r_igv,
  r_monto_total,
  COALESCE(precio_chofer, 0) AS precio_chofer,
  porc_igv,
  condicion_pago,
  contra,
  CAST(llegada_aprox AS VARCHAR(50)) AS llegada_aprox,
  TO_CHAR(llegada_real, 'YYYY-MM-DD HH24:MI:SS') AS llegada_real,
  numero_rdi,
  r_vfirmado,
  cdr_descripcion,
  estado_sunat,
  COALESCE(registrado, 1)::integer AS registrado,
  ctrl_crea,
  ctrl_crea_us,
  ctrl_mod,
  ctrl_mod_us
`;
// Proyeccion con alias de tabla. La usa el listado de operaciones, que necesita
// calificar cada columna con el alias de la tabla principal.
const columnasVentaTransDesde = (alias) => `
  CAST(${alias}.r_fecemi AS VARCHAR(50)) AS r_fecemi,
  ${alias}.r_cod,
  ${alias}.r_serie,
  ${alias}.r_numero,
  ${alias}.elemento,
  ${alias}.tipo_operacion,
  ${alias}.r_cod_ref,
  ${alias}.r_serie_ref,
  ${alias}.r_numero_ref,
  CAST(${alias}.r_fecemi_ref AS VARCHAR(50)) AS r_fecemi_ref,
  ${alias}.cliente_id_doc AS id_documento,
  ${alias}.cliente_id_doc,
  ${alias}.cliente,
  ${alias}.cliente_documento_id AS cliente_documento,
  ${alias}.cliente_documento_id,
  ${alias}.cliente_telefono,
  ${alias}.cliente_direccion_fact,
  ${alias}.ref_pasajero_dni,
  ${alias}.ref_pasajero_nombres,
  ${alias}.id_punto_venta,
  ${alias}.cliente_zona AS remitente_zona,
  ${alias}.cliente_zona,
  ${alias}.cliente_direccion AS remitente_direccion,
  ${alias}.cliente_direccion,
  ${alias}.id_ruta,
  ${alias}.descripcion,
  ${alias}.placa,
  ${alias}.licencia,
  ${alias}.id_manifiesto,
  ${alias}.asiento,
  ${alias}.pasajero_edad,
  ${alias}.destinatario_id_doc,
  ${alias}.destinatario,
  ${alias}.destinatario_documento_id AS destinatario_documento,
  ${alias}.destinatario_documento_id,
  ${alias}.destinatario_telefono,
  ${alias}.id_punto_venta_dest,
  ${alias}.destinatario_zona,
  ${alias}.destinatario_direccion,
  CAST(${alias}.entrega_fecha AS VARCHAR(50)) AS entrega_fecha,
  ${alias}.entrega_documento_id AS entrega_documento,
  ${alias}.entrega_documento_id,
  ${alias}.entrega_nombres,
  ${alias}.entrega_ctrl_us,
  1 AS cantidad,
  ${alias}.precio_neto AS precio_unitario,
  ${alias}.precio_neto,
  ${alias}.r_gravado,
  ${alias}.r_exonerado,
  ${alias}.r_igv,
  ${alias}.r_monto_total,
  COALESCE(${alias}.precio_chofer, 0) AS precio_chofer,
  ${alias}.porc_igv,
  ${alias}.condicion_pago,
  ${alias}.contra,
  CAST(${alias}.llegada_aprox AS VARCHAR(50)) AS llegada_aprox,
  TO_CHAR(${alias}.llegada_real, 'YYYY-MM-DD HH24:MI:SS') AS llegada_real,
  ${alias}.numero_rdi,
  ${alias}.r_vfirmado,
  ${alias}.cdr_descripcion,
  ${alias}.estado_sunat,
  COALESCE(${alias}.registrado, 1)::integer AS registrado,
  ${alias}.ctrl_crea,
  ${alias}.ctrl_crea_us,
  ${alias}.ctrl_mod,
  ${alias}.ctrl_mod_us
`;

module.exports = {
  columnasVentaTrans,
  columnasVentaTransDesde
};
