// Proyeccion compartida de mve_transventa.
//
// Se extrajo del controller historico porque la usan el CRUD de transporte
// (crear, listar, detalle, actualizar, anular) y tambien el flujo de
// encomiendas en agencia destino. Vive en un modulo neutro para no duplicarla
// ni para que el repository dependa del controller.
//
// No modificar ni una coma: los nombres de columna son el contrato del frontend.
const columnasVentaTrans = `
  CAST(r_fecemi AS VARCHAR(50)) AS r_fecemi,
  r_cod,
  r_serie,
  r_numero,
  elemento,
  tipo_operacion,
  r_cod_ref,
  r_serie_ref,
  r_numero_ref,
  CAST(r_fecemi_ref AS VARCHAR(50)) AS r_fecemi_ref,
  cliente_id_doc AS id_documento,
  cliente_id_doc,
  cliente,
  cliente_documento_id AS cliente_documento,
  cliente_documento_id,
  cliente_telefono,
  cliente_direccion_fact,
  id_punto_venta,
  cliente_zona AS remitente_zona,
  cliente_zona,
  cliente_direccion AS remitente_direccion,
  cliente_direccion,
  id_ruta,
  descripcion,
  placa,
  licencia,
  asiento,
  pasajero_edad,
  destinatario_id_doc,
  destinatario,
  destinatario_documento_id AS destinatario_documento,
  destinatario_documento_id,
  destinatario_telefono,
  id_punto_venta_dest,
  destinatario_zona,
  destinatario_direccion,
  CAST(entrega_fecha AS VARCHAR(50)) AS entrega_fecha,
  entrega_documento_id AS entrega_documento,
  entrega_documento_id,
  entrega_nombres,
  entrega_ctrl_us,
  1 AS cantidad,
  precio_neto AS precio_unitario,
  precio_neto,
  r_gravado,
  r_exonerado,
  r_igv,
  r_monto_total,
  COALESCE(precio_chofer, 0) AS precio_chofer,
  porc_igv,
  condicion_pago,
  contra,
  CAST(llegada_aprox AS VARCHAR(50)) AS llegada_aprox,
  TO_CHAR(llegada_real, 'YYYY-MM-DD HH24:MI:SS') AS llegada_real,
  numero_rdi,
  r_vfirmado,
  cdr_descripcion,
  estado_sunat,
  COALESCE(registrado, 1)::integer AS registrado,
  ctrl_crea,
  ctrl_crea_us,
  ctrl_mod,
  ctrl_mod_us
`;
module.exports = { columnasVentaTrans };
